### ISSUE TITLE
Make jaraco.mongodb.service an optional extra

### ISSUE THREAD

**Issue by bdeeney** [jaraco/jaraco.mongodb#23]
We have several downstream projects which make use of portions of `jaraco.mongodb` (specifically, the `sessions` and `migration` modules), but do not rely on `jaraco.mongodb.service`. Unfortunately, the latter introduces a large number of dependencies that are not otherwise required by `jaraco.mongodb` or our downstream projects.  Defining `jaraco.mongodb.service` as an optional "extra" would significantly reduce the weight of the `jaraco.mongodb` dependency graph.

**Comment by jaraco** [comment]
After reviewing, I found that `jaraco.services.envs` was the sole dependency on virtualenv and tox and had little in common with other jaraco.services modules and zero dependency, so I split that module into its own package. `jaraco.mongodb` will automatically pick up `jaraco.services` 3.0. Other projects depending on jaraco.services.envs will need to pin to `jaraco.services` 2 or (preferably) update to use `jaraco.envs`.
